### ISSUE TITLE
Search Display Updates

### ISSUE THREAD

**Issue by marques-j-robinson** [mantisg/Spicy-Weather#4]
Should render a search button and no input text as default.
When search button is clicked, update search button text to display an 'X' icon and the onPress to toggle the search display state. An input element should display to the left of the button when the search display state is `true` and hide the element when the  search display state is `false`.

Bonus if you can custom style it with the x button actually appearing in the search text box with a translucent background. That's kinda a trick css thing, but a rabbit hole none the less!

**Comment by mantisg** [comment]
Sadly, I haven't yet figured out how to do the translucent background in the text box, but the functionality of the clear and exit buttons are there and neatly packaged with the search bar. Maybe later you can show me how to put the X in the text box to make it a little cleaner. ONWARD TO FUNCTIONALITY!!!!
